---
- name: Add Erlang repository key
  apt_key: url=http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present
  sudo: yes

- name: Add the Erlang repository
  apt_repository: repo='deb http://packages.erlang-solutions.com/ubuntu trusty contrib' state=present
  sudo: yes

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes

- name: Install Erlang and Elixir
  sudo: yes
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - erlang
    - elixir
